name: Deploy Functions

on:
  push:
    branches:
      - master
    paths:
      - "functions/**"

defaults:
  run:
    working-directory: ./functions

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: yarn install
      - name: Install Firebase
        run: sudo yarn global add firebase-tools
      - name: Deploy
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
