name: Fetch Offerings
on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        working-directory: ./functions
        run: yarn install
      - name: Run Build Script
        working-directory: ./functions
        run: node -r esm index.js
      - name: Commit results
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git add --all
          git commit --allow-empty -m "chore: sync application data"
          git push origin main
