name: Release

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Install Firebase
        run: sudo yarn global add firebase-tools
      - name: Deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
